apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
 #   cloud.google.com/load-balancer-type: "Internal"
  name: prometheus-service
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector: 
    app: prometheus-server 
  ports: 
    - name: prometheus 
      port: 9090
      targetPort: 9090
      nodePort: 32001
  type: NodePort
