{
 "title": "K8s Cluster Summary",
 "description": "Summary metrics about containers running on Kubernetes nodes and mainline kubernetes statistics",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Control Plane Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane Status",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-apiserver-.*\"}) + sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-controller-manager-.*\"}) + sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-scheduler-.*\"}) + sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-proxy.*\"}) + sum(kube_pod_status_ready{condition=\"true\",pod=~\"coredns-.*\"}) + sum(kube_pod_status_ready{condition=\"true\",pod=~\"calico-node-.*\"})"
      }
     ]
    },
    {
     "title": "Available Kube-Apiserver",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-apiserver-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Api-Server Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"kube-apiserver-.*\"}\t"
      }
     ]
    },
    {
     "title": "Api-Server [rpm]",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[1m]))",
       "legendFormat": "RPM"
      }
     ]
    },
    {
     "title": "[API] Failed Requests [opm]",
     "type": "graph",
     "description": "[rate 1m] [opm]",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "ops/m" }
     ],
     "targets": [
      {
       "expr": "max(changes(apiserver_request_total{code=~\"5..\"}[1m])) by (code,verb,client,resource) > 0",
       "legendFormat": "{{resource}} / {{verb}} / {{client}} / {{code}} "
      }
     ]
    },
    {
     "title": "Available ETCD",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"etcd-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes ETCD Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"etcd-.*\"}\t"
      }
     ]
    },
    {
     "title": "ETCD [rps]",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",job=\"kubernetes-etcd\"}[5m]))"
      }
     ]
    },
    {
     "title": "[ETCD] FAILED Requests [ops]",
     "type": "graph",
     "description": "[rate 1m] [ops]",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "ops", "label": "Ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",job=\"kubernetes-etcd\"}[5m])) by (grpc_code)",
       "legendFormat": "{{pod_name}} / {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Available Kube-Scheduler",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-scheduler-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Scheduler Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 18 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"kube-scheduler-.*\"}\t"
      }
     ]
    },
    {
     "title": "Available Kube-Controller-Manager",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-controller-manager-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Controller-Manager Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"kube-controller-manager-.*\"}\t"
      }
     ]
    },
    {
     "title": "Available CoreDNS",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"coredns-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes CoreDNS Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 24 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"coredns-.*\"}\t"
      }
     ]
    },
    {
     "title": "Available Kube-Proxy",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-proxy.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Proxy Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"kube-proxy-.*\"}\t"
      }
     ]
    },
    {
     "title": "Available Calico-Node",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"calico-node-.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Calico-Node Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 30 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"calico-node-.*\"}\t"
      }
     ]
    },
    {
     "title": "Available Node-Exporter",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"node-exporter.*\"})"
      }
     ]
    },
    {
     "title": "Kubernetes Node Exporter Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Running\",pod=~\"node-exporter.*\"}\t"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Pod Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Disk Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (node_filesystem_size_bytes{nodename=~\"$node\"}) - sum (node_filesystem_free_bytes{nodename=~\"$node\"})) / sum (node_filesystem_size_bytes{nodename=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Pod Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "pods" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster Mem Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster Disk Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{nodename=~\"$node\"}) - sum(node_filesystem_free_bytes{nodename=~\"$node\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{nodename=~\"$node\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Disk Usage of /",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\"$node\"}) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" =~ /^$node$/ AND \"fstype\" != 'nfs' AND \"fstype\" != 'iso9660' AND \"path\" = '/') AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Usage of /app",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\"$node\"}) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" =~ /^$node$/ AND \"fstype\" != 'nfs' AND \"fstype\" != 'iso9660' AND \"path\" = '/app') AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace!=\"kube-system\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Configmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Configmap Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "ConfigMap List",
     "type": "table",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
     "targets": [
      {
       "expr": "kube_configmap_info{namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account-API-Model Pod",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"pod-dloan-account-api-model-.*\"})"
      }
     ]
    },
    {
     "title": "Account-API-Model Pod List",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 9 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"pod-dloan-account-api-model-.*\"} > 0"
      },
      {
       "expr": "kube_pod_created{pod=~\"pod-dloan-account-api-model-.*\"} * 1000"
      },
      {
       "expr": "kube_pod_info{pod=~\"pod-dloan-account-api-model-.*\"} + 0"
      }
     ]
    },
    {
     "title": "Account-API-Rest Pod",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"pod-dloan-account-api-rest-.*\"})"
      }
     ]
    },
    {
     "title": "Account-API-Rest Pod List",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 14 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"pod-dloan-account-api-rest-.*\"} > 0"
      },
      {
       "expr": "kube_pod_created{pod=~\"pod-dloan-account-api-rest-.*\"} * 1000"
      },
      {
       "expr": "kube_pod_info{pod=~\"pod-dloan-account-api-rest-.*\"} + 0"
      }
     ]
    },
    {
     "title": "Account Producer Open Account Pod",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"pod-dloan-account-producer-open-account-.*\"})"
      }
     ]
    },
    {
     "title": "Account-Producer-Open-Account Pod List",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 19 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"pod-dloan-account-producer-open-account-.*\"} > 0"
      },
      {
       "expr": "kube_pod_created{pod=~\"pod-dloan-account-producer-open-account-.*\"} * 1000"
      },
      {
       "expr": "kube_pod_info{pod=~\"pod-dloan-account-producer-open-account-.*\"} + 0"
      }
     ]
    },
    {
     "title": "Account-Streamer Pod",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"pod-dloan-account-streamer-.*\"})"
      }
     ]
    },
    {
     "title": "Account-Streamer Pod List",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 24 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"pod-dloan-account-streamer-.*\"} > 0"
      },
      {
       "expr": "kube_pod_created{pod=~\"pod-dloan-account-streamer-.*\"} * 1000"
      },
      {
       "expr": "kube_pod_info{pod=~\"pod-dloan-account-streamer-.*\"} + 0"
      }
     ]
    },
    {
     "title": "Account-Yotta Pod",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"pod-dloan-account-yotta-.*\"})"
      }
     ]
    },
    {
     "title": "Account-Yotta Pod List",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 29 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"pod-dloan-account-yotta-.*\"} > 0"
      },
      {
       "expr": "kube_pod_created{pod=~\"pod-dloan-account-yotta-.*\"} * 1000"
      },
      {
       "expr": "kube_pod_info{pod=~\"pod-dloan-account-yotta-.*\"} + 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pods Lag",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expression": "A['pod_dc']-B['pod_dr']", "outputMetricName": "Pod Lag", "periods": 7, "timeshiftUnit": "days" }
     ]
    },
    {
     "title": "Total Pods Lag Between DC and DR",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expression": "A['pod_dc'] - B['pod_dr']", "outputMetricName": "Lag Between DC and DR", "periods": 7, "timeshiftUnit": "days" }
     ]
    }
   ]
  }
 ]
}